## Step 1: Setup Dataset

In [1]:
import numpy as np

data = np.array([
    [501,45,3,120,60],
    [502,30,2,80,50],
    [503,60,4,np.nan,70],
    [504,25,1,60,40],
    [505,80,5,200,90],
    [506,-20,2,70,50],
    [507,35,2,90,55],
    [508,50,3,np.nan,65],
    [509,90,6,250,100],
    [510,200,4,150,80],
    [511,55,3,110,60],
    [512,40,2,95,55]
])

print("Dataset shape:", data.shape)


Dataset shape: (12, 5)


## Step 2: Indexing & Slicing

In [2]:
print("First 5 players:\n", data[:5])
print("Session durations:\n", data[:,1])
print("Single player (ID 505):\n", data[4])

First 5 players:
 [[501.  45.   3. 120.  60.]
 [502.  30.   2.  80.  50.]
 [503.  60.   4.  nan  70.]
 [504.  25.   1.  60.  40.]
 [505.  80.   5. 200.  90.]]
Session durations:
 [ 45.  30.  60.  25.  80. -20.  35.  50.  90. 200.  55.  40.]
Single player (ID 505):
 [505.  80.   5. 200.  90.]


## Step 3: Basic Analysis

In [3]:
avg_duration = np.nanmean(data[:,1])   # handle NaN
max_duration = np.nanmax(data[:,1])
min_duration = np.nanmin(data[:,1])
avg_levels = np.nanmean(data[:,2])
total_actions = np.nansum(data[:,3])

print("Average session duration:", avg_duration)
print("Max duration:", max_duration)
print("Min duration:", min_duration)
print("Average levels completed:", avg_levels)
print("Total actions:", total_actions)

Average session duration: 57.5
Max duration: 200.0
Min duration: -20.0
Average levels completed: 3.0833333333333335
Total actions: 1225.0


## Step 4: Vectorization

In [4]:
bonus_actions = np.where(np.isnan(data[:,3]), np.nan, data[:,3] + 10)
high_performers = data[data[:,2] > 4]
low_activity = data[data[:,3] < 80]

print("Bonus actions:", bonus_actions)
print("High performers:\n", high_performers)
print("Low activity players:\n", low_activity)

Bonus actions: [130.  90.  nan  70. 210.  80. 100.  nan 260. 160. 120. 105.]
High performers:
 [[505.  80.   5. 200.  90.]
 [509.  90.   6. 250. 100.]]
Low activity players:
 [[504.  25.   1.  60.  40.]
 [506. -20.   2.  70.  50.]]


## Step 5: Feature Engineering

In [5]:
performance_score = data[:,2] / np.where(data[:,1] <= 0, np.nan, data[:,1])
data = np.column_stack((data, performance_score))

print("Dataset with Performance Score:\n", data)

Dataset with Performance Score:
 [[ 5.01000000e+02  4.50000000e+01  3.00000000e+00  1.20000000e+02
   6.00000000e+01  6.66666667e-02]
 [ 5.02000000e+02  3.00000000e+01  2.00000000e+00  8.00000000e+01
   5.00000000e+01  6.66666667e-02]
 [ 5.03000000e+02  6.00000000e+01  4.00000000e+00             nan
   7.00000000e+01  6.66666667e-02]
 [ 5.04000000e+02  2.50000000e+01  1.00000000e+00  6.00000000e+01
   4.00000000e+01  4.00000000e-02]
 [ 5.05000000e+02  8.00000000e+01  5.00000000e+00  2.00000000e+02
   9.00000000e+01  6.25000000e-02]
 [ 5.06000000e+02 -2.00000000e+01  2.00000000e+00  7.00000000e+01
   5.00000000e+01             nan]
 [ 5.07000000e+02  3.50000000e+01  2.00000000e+00  9.00000000e+01
   5.50000000e+01  5.71428571e-02]
 [ 5.08000000e+02  5.00000000e+01  3.00000000e+00             nan
   6.50000000e+01  6.00000000e-02]
 [ 5.09000000e+02  9.00000000e+01  6.00000000e+00  2.50000000e+02
   1.00000000e+02  6.66666667e-02]
 [ 5.10000000e+02  2.00000000e+02  4.00000000e+00  1.50000

## Step 6: Data Cleaning

In [6]:
# Replace NaN with mean of column
col_means = np.nanmean(data, axis=0)
inds = np.where(np.isnan(data))
data[inds] = np.take(col_means, inds[1])

# Replace negative values in session_duration with mean
data[:,1] = np.where(data[:,1] < 0, col_means[1], data[:,1])

# Handle outliers (mean ± 2*std)
mean_duration = np.mean(data[:,1])
std_duration = np.std(data[:,1])
upper_limit = mean_duration + 2*std_duration
lower_limit = mean_duration - 2*std_duration
data[:,1] = np.clip(data[:,1], lower_limit, upper_limit)

print("Cleaned dataset:\n", data)

Cleaned dataset:
 [[5.01000000e+02 4.50000000e+01 3.00000000e+00 1.20000000e+02
  6.00000000e+01 6.66666667e-02]
 [5.02000000e+02 3.00000000e+01 2.00000000e+00 8.00000000e+01
  5.00000000e+01 6.66666667e-02]
 [5.03000000e+02 6.00000000e+01 4.00000000e+00 1.22500000e+02
  7.00000000e+01 6.66666667e-02]
 [5.04000000e+02 2.50000000e+01 1.00000000e+00 6.00000000e+01
  4.00000000e+01 4.00000000e-02]
 [5.05000000e+02 8.00000000e+01 5.00000000e+00 2.00000000e+02
  9.00000000e+01 6.25000000e-02]
 [5.06000000e+02 5.75000000e+01 2.00000000e+00 7.00000000e+01
  5.00000000e+01 5.55322708e-02]
 [5.07000000e+02 3.50000000e+01 2.00000000e+00 9.00000000e+01
  5.50000000e+01 5.71428571e-02]
 [5.08000000e+02 5.00000000e+01 3.00000000e+00 1.22500000e+02
  6.50000000e+01 6.00000000e-02]
 [5.09000000e+02 9.00000000e+01 6.00000000e+00 2.50000000e+02
  1.00000000e+02 6.66666667e-02]
 [5.10000000e+02 1.53806778e+02 4.00000000e+00 1.50000000e+02
  8.00000000e+01 2.00000000e-02]
 [5.11000000e+02 5.50000000e+01 